### PR TITLE
Removed GitPython dependency.

### PR DESCRIPTION
**Pull request by oadams**
This addon caused a number of install issues which were non-trivial to fix. However, the use of the addon was fairly specific to my experimentation of different architectures back in the day. The idea was to 1) store the exact git has of the commit I was on 2) ensure there weren't any uncommitted changes. This was so that when writing a paper I would note down which commit I got results from.

However, this is no longer relevant since the Persephone architecture is unlikely to change and for the purposes of other users, storing persephone.__version__ is likely to be good enough (and that still gets stored in the experiment directory).

### CODE REVIEW

**Comment by shuttle1987** [comment]
Generally speaking I'd be in favor of storing this metadata in the `__version__` and removing the gitpython dependency entirely. I think the removal of GitPython as a dependency should be recorded with at least a patch version bump

**Comment by oadams** [comment]
Yeah the code writes `persephone.__version__` to the experiment directory. I included in the PR a patch bump in setup.py. When @BenjaminGalliot confirms it fixes the bug at his end I'll push to pypi.

**Comment by BenjaminGalliot** [comment]
It works now in a fresh new venv for Elpis, problem solved, at least with the `corpus_reader` import (where it crashes usually)!

I just noticed that `__version__` variable in `__init__.py` file is still `0.4.1`, compared to `0.4.2` in `setup.py` file.

```
root@b0030e861869:/elpis/persephone# pip3 list
absl-py (0.9.0)
appdirs (1.4.3)
astor (0.8.1)
astroid (2.3.3)
attrs (19.3.0)
click (7.1.1)
elpis (0.93.8, /elpis)
Flask (1.1.2)
gast (0.3.3)
google-pasta (0.2.0)
grpcio (1.28.1)
h5py (2.10.0)
importlib-metadata (1.6.0)
isort (4.3.21)
itsdangerous (1.1.0)
Jinja2 (3.0.0a1)
joblib (0.14.1)
Keras-Applications (1.0.8)
Keras-Preprocessing (1.1.0)
langid (1.1.6)
lazy-object-proxy (1.4.3)
Markdown (3.2.1)
MarkupSafe (2.0.0a1)
mccabe (0.6.1)
more-itertools (8.2.0)
nltk (3.4.5)
numpy (1.18.2)
packaging (20.3)
persephone (0.4.2)
Pint (0.9)
pip (9.0.1)
pkg-resources (0.0.0)
pluggy (0.13.1)
praatio (4.0.0)
protobuf (3.11.3)
py (1.8.1)
pydub (0.20.0)
pylint (2.4.4)
pympi-ling (1.69)
pyparsing (2.4.7)
pystache (0.5.4)
pytest (5.4.1)
python-speech-features (0.6)
regex (2020.4.4)
scikit-learn (0.21.2)
scipy (1.4.1)
setuptools (46.1.3)
six (1.14.0)
tensorboard (1.14.0)
tensorflow (1.14.0)
tensorflow-estimator (1.14.0)
termcolor (1.1.0)
tqdm (4.45.0)
typed-ast (1.4.1)
wcwidth (0.1.9)
Werkzeug (1.0.1)
wheel (0.34.2)
wrapt (1.11.2)
zipp (3.1.0)
root@b0030e861869:/elpis/persephone# python3
Python 3.6.9 (default, Nov  7 2019, 10:44:02) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import persephone
>>> from persephone import corpus_reader
>>> persephone.__version__
'0.4.1'
>>> 
```

**Comment by shuttle1987** [comment]
@BenjaminGalliot thanks for this info, this happens because: https://github.com/persephone-tools/persephone/blob/826a55917137fb30e816eaf6741a279a9789907d/persephone/__init__.py#L1 has not yet been updated

**Comment by shuttle1987** [comment]
This strikes me as a super strange test error and I suspect it's not something to do with any of the Persephone code.

**Comment by oadams** [comment]
Yeah same I was confused. But figured it's about time we let go of Python 3.5 anyway, so it looks all good now.

**Comment by shuttle1987** [comment]
I think this should be merged in sooner rather than later

**Pull request merged**
