### PR TITLE
[MRG] Improve CorpusReader.train_batch_gen in edge case situation

### LINKED ISSUE #184: Training fails with non intuitive reason when train_batch_gen produces no data
If the `CorpusReader` ends up with `num_train` being 0 it will not generate batches properly because:

```python
    def train_batch_gen(self):
        """ Returns a generator that outputs batches in the training data."""

        # Create batches of batch_size and shuffle them.
        fn_batches = self.make_batches(self.train_fns)
        if self.rand:
            random.shuffle(fn_batches)

        for fn_batch in fn_batches:
            logger.debug("Batch of training filenames: %s",
                          pprint.pformat(fn_batch))
            yield self.load_batch(fn_batch)
```
Won't yield anything and then this will end up failing on model training with a rather cryptic error:

```
    response = function(request)
  File "/home/janis/persephone-web-API/venv/lib/python3.5/site-packages/connexion/decorators/parameter.py", line 219, in wrapper
    return function(**kwargs)
  File "/home/janis/persephone-web-API/persephone_api/api_endpoints/model.py", line 110, in train
    MAX_EPOCHS = 100 # TODO: Set maximum running time somewhere else
  File "/home/janis/persephone/persephone/model.py", line 323, in train
    epoch, (train_ler_total / (batch_i + 1)), valid_ler, valid_per)
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'
```

I propose we bail out much earlier when this is detected.

### PR DESCRIPTION
**Pull request by shuttle1987**
- [x] Give better error reporting on CorpusReader being in invalid state, Closes #184

### CODE REVIEW

**Comment by oadams** [comment]
I agree that the message in #184 should not be cryptic, but I don't agree with the proposed solution in this PR. A Corpus may simply be comprised of untranscribed utterances to be transcribed, and not have any paired speech and transcriptions. The train_batch_gen() generator should either raise that exception or perhaps just StopIteration.

**Comment by shuttle1987** [comment]
I guess I don't fully understand what the `CorpusReader` is supposed to be doing then. I changed `train_batch_gen` to raise StopIteration. This will however still have a strange situation if the loop doesn't run where:

```python
                    epoch_str = "Epoch %d. Training LER: %f, validation LER: %f, validation PER: %f" % (
                        epoch, (train_ler_total / (batch_i + 1)), valid_ler, valid_per)
```
Will now give a `NameError` on `batch_i` if it didn't get created by the `enumerate` loop. On a symptomatic level I can see doing something like a try/except for the `NameError` to generate a more suitable error message but I'd like to be a bit more confident I know the intentions of the code here first before doing that.

Also I think there's a few other places where functions that are supposed to be `yield`ing values are returning `None` which might lead to some errors.

**Comment by shuttle1987** [comment]
This is ready to merge, I think it would be good to address the error message though. If no batches are created for training I think we should bail out the training by throwing a `PersephoneError` exception instead of just letting the code fail at some later unspecified point.

**Comment by shuttle1987** [comment]
So I have a failing test case over on the Web-API https://github.com/persephone-tools/persephone-web-API/pull/82 . It's not clear why this is failing, which makes me think that we should work on cleaning up the documentation on this area.

**Comment by oadams** [comment]
> This is ready to merge, I think it would be good to address the error message though. If no batches are created for training I think we should bail out the training immediately by throwing a PersephoneError exception instead of just letting the code fail at some later unspecified point.

I agree that training should throw a PersephoneException immediately if there are no batches.

> I guess I don't fully understand what the CorpusReader is supposed to be doing then.

CorpusReader's role is just to load data specified by a Corpus. However, the tricky thing is that Corpus objects vary in what they are, so I'll take a step back here: The main cases I can see are corpora with (a) paired speech utterances with transcriptions (this can be used for training), (b) untranscribed speech that the tool is meant to transcribe, or some combination of (a) and (b).

The combination case is useful and is the most common case. It's useful to address because a linguist can conceivably just point to a whole directory and then a Corpus object is created that represents the collection they have. Persephone can then help them fill in the gaps by training a model on paired speech where available, and then transcribing what is untranscribed.

Some amount of the training data is left out by default in Corpus creation and comprise the dev and tests so that the error rate of models can be quantified.

**Comment by shuttle1987** [comment]
I think that CorpusReader and Corpus don't require any changes, however I'd like to change the logic of the training to bail out with an error if no training batches are found.

**Pull request merged**
