### PR TITLE
[MRG] Clean up Model

### LINKED ISSUE #138: model.train docstring is out of date
```
    def train(self, early_stopping_steps=10, min_epochs=30, max_valid_ler=1.0,
              max_train_ler=0.3, max_epochs=100, restore_model_path=None):
        """ Train the model.

            batch_size: The number of utterances in each batch.
            total_size: The number of TIMIT training examples to use.
            num_epochs: The number of times to iterate over all the training
                        examples.
            feat_type:  Is the identifier for the type of features we're using.
                        'mfcc13_d' means MFCCs of 13 dimensions with their first
                        derivatives.
            save_n: Whether to save the model at every n epochs.
            restore_model_path: The path to restore a model from.
        """
```

Currently there's some parameters that are not matching what is in the docstring.

### LINKED ISSUE #145: Speakers parameter in `Corpus` is unused
Currently the `speakers` parameter in `Corpus.__init__` is unused.

This strikes me as an issue because `fromElan` call `Corpus` constructor with this parameter but then nothing happens.

### PR DESCRIPTION
**Pull request by shuttle1987**
Clean up Model code

Code quality:
- [x] Improve code around stopping criteria
- [x] Deal with unused parameter for `speakers`
- [x] Move `Model` class variables to instance variables
- [x] remove unused variables #152 

Documentation:
- [x] Fix `model.train` docstring (Closes #138)
- [x] Document instance variables for `Model` (depends on task above)

Deferred:
- Serialize model descriptions (`write_desc`) with a standard format, see issues #154, #153

### CODE REVIEW

**Comment by shuttle1987** [comment]
FYI this is currently failing on CI due to a mypy type check not working, all unit tests pass.

**Comment by shuttle1987** [comment]
Does anything explicitly rely on the path for `model_description.txt`? I would like to change this to something like `model_description.json` if encoded with JSON

**Comment by shuttle1987** [comment]
Now that the requested changes have been made and the tests are passing again it would be good to merge this soon. A complete test run would be good at this point.

**Comment by shuttle1987** [comment]
Improving how we serialize model descriptions  is something that I think would benefit from some discussion so I have struck this off this PR. Should be ready to merge when we have run the tests

**Comment by oadams** [comment]
> Does anything explicitly rely on the path for model_description.txt? I would like to change this to something like model_description.json if encoded with JSON

Nothing depends on that, so go for it. But I think the description of models may need to be fundamentally changed, not just to JSON. Or more generally, the description of an experiment

> I've improved some of the code around the stopping criteria but I'll leave it up to your judgment if you think this resolves #79 or if there is still more work to do there.

Good job! I think there's still more for me to do, so I'll leave it open for now.

> Now that the requested changes have been made and the tests are passing again it would be good to merge this soon as this PR is getting quite big already. A complete test run would be good at this point.

Running tests now.

**Comment by shuttle1987** [comment]
Good catch, I see how I introduced this change in the refactor. I I think we really need to have a format for these logs and then write unit tests against them if they are being relied upon.

**Comment by shuttle1987** [comment]
In attempting to reduce the level of nesting I introduced the previous bug. I think this is fixed now and that once we clear up the logging format we will get value from having a test case for these logs.

**Pull request merged**
