### PR TITLE
[MRG] Work on standalone model decoding function

### LINKED ISSUE #90: Add type signatures to just about everything
I say "just about" because there may be cases for not typing some things.

### LINKED ISSUE #158: Filesystem artifacts need tests
Since information is stored in the filesystem about various aspects of the training process such as `train_log.txt` it would be good to get some test coverage.

### LINKED ISSUE #166: Create minimal test corpus
I really want to make a test of corpus construction that does a more complete end to end test run without depending on pulling in external data. I have a few such cases from PR #163  that will test for various things like exceptions thrown on directory structure missing and the like. I started trying to put together a more pure test case for corpus construction in 7a3cb14 but I hit a bit of a roadblock because the ffmpeg call will fail on the non-wav data contained in the .wav mock files.

Right now a vague plan I have in mind is to make a data set with a single phoneme and only 3 files, one file for testing, one file for training and one file for validation. The labels would be the one phoneme for each of those files. The wav files could be a recording of those single phonemes then encoded as a string that can be directly written to the wav file in the test case (something like base64 for example).

Having such a `Corpus` would make it much easier for us to increase test coverage on important code paths.

### PR DESCRIPTION
**Pull request by shuttle1987**
This is for use with the web API to decode audio files using existing trained models.

* [x] Created minimal test corpus, closes #166
* [x] Test filesystem based API for saving and loading models, closes #158 
* [x] Added missing type stubs, closes #90

### CODE REVIEW

**Comment by shuttle1987** [comment]
I'm thinking it might be good to provide a parameter to the `persephone.model.decode` function to specify the names of the inputs.

Right now we have the following:

```python
        # TODO These placeholder names should be a backup if names from a newer
        # naming scheme aren't present. Otherwise this won't generalize to
        # different architectures.
        feed_dict = {"Placeholder:0": batch_x,
                     "Placeholder_1:0": batch_x_lens}

        dense_decoded = sess.run("SparseToDense:0", feed_dict=feed_dict)
```

I propose that we create a parameters for:
* `batch_x` name for the location for where the batch data is being fed in
* `batch_x_lens` name for the location for where the lengths of the batch data is being fed in

We can default both these to their current placeholder values if they are not specified.

**Comment by shuttle1987** [comment]
I successfully did a run through with this and it works. I would very much like to create a test case for this.

**Comment by shuttle1987** [comment]
Just putting in the work to get a test case that can run this through in it's entirety. There's some bugs that appear to be getting uncovered from doing this. At the point there are a couple of failing test cases but this might be just due to the tests not being right.

**Comment by shuttle1987** [comment]
It appears that calling `Corpus.__init__` with no labels parameter can fail if the size of the incoming data is too small. I think this is due to an issue with the training splits functionality not creating the right data set size in the case of small numbers of files being available (hence 5% of 3 files gets rounded down to zero type of edge case). Perhaps this should have a minimum or raise some sort of error?

**Comment by shuttle1987** [comment]
Took a bit of messing around but we now have FFMPEG installed in travis so we can actually do a proper non-mocked test case for this now.

**Comment by shuttle1987** [comment]
The test case written in https://github.com/persephone-tools/persephone/pull/197/commits/ff6d9584dfd9a772c87304d6d42ab733f5e1cda7 actually exposes a bit of a nasty edge case, if the model never satisfies this conditional in the training:

```python
                    if valid_ler < best_valid_ler:
```
Then it never saves a checkpoint file and the evaluation will fail at the end of the `Model.train` method.

**Comment by oadams** [comment]
> The test case written in [ff6d958](https://github.com/persephone-tools/persephone/commit/ff6d9584dfd9a772c87304d6d42ab733f5e1cda7) actually exposes a bit of a nasty edge case, if the model never satisfies this conditional in the training:
> 
> ```python
>                     if valid_ler < best_valid_ler:
> ```
> 
> Then it never saves a checkpoint file and the evaluation will fail at the end of the `Model.train` method.

Just initialize best_valid_ler to a large number so that a model always gets saved. It's currently 2.0.

**Comment by shuttle1987** [comment]
> What corpus are you currently using? If the sine wave test is correct I imagine it should pretty immediately get 100% accuracy.
A bad one, where:
* test: A
* validation: B
* training: C

With no overlap from any of these the results ended up being a degenerate case I suspect.

**Comment by shuttle1987** [comment]
> Just initialize best_valid_ler to a large number so that a model always gets saved. It's currently 2.0.

This is something I didn't consider when writing the test case, it might be a good thing to use to reduce the unit test time in this case.

**Comment by shuttle1987** [comment]
There's quite a few significant changes in this PR and it will unblock work on the web API. As such it would be good to release a new version after this is merged.

**Comment by shuttle1987** [comment]
I think I'd just test on a WAV seen in training, the purpose of these tests was just to have coverage over the non-Tensorflow model parts of the code without having to run the much slower experiment test suite containing real data. Now that said if there's a way of making this sample data test work better that has value in testing the model as well that could be good for a separate test case. The value of a good test of the model is somewhat orthogonal to tests of the code _around_ the model.

**Comment by shuttle1987** [comment]
I had considered fixing #153 in this PR but I hesitate to make more change here as this PR is at a somewhat stable state and is already over 50 commits. Seeing as this PR will unblock work on the Web API I would like to focus on finalizing anything that's required to merge this one in.

As for integration testing times is this something a GPU based install could help with or are we needing to specifically test on CPU as well?

**Comment by oadams** [comment]
Note, it doesn't always output empty lists, but it's. It's just clear a better corpus and training procedure is needed. I can fix this sometime.  The best thing to do would just be to add a test for the decode() function into the integration test that tests the tutorial, that way we can confirm its working. We can go ahead and merge this in and release to forge ahead with the web API.

**Comment by shuttle1987** [comment]
> The best thing to do would just be to add a test for the decode() function into the integration test that tests the tutorial, that way we can confirm its working

I agree that this is the best way forward, if this is something you could do that would be great.

Would a JSON formatted data output from the model description help this? If so I can put those changes into this PR as well.

**Comment by oadams** [comment]
Yeah, I'll do it.

Yes to JSON if it's a super quick job. Something formatted better than the current text files would be good, but that said this is for human readability and those text files do already do the job.

**Pull request merged**
