### PR TITLE
[MRG] Fix issues with feature extraction and empty wav files

### LINKED ISSUE #52: If there's an issue in the transcription file and WAVs are empty, present a warning on feature extraction, skipping the file instead of crashing

### PR DESCRIPTION
**Pull request by shuttle1987**
Fix issue with crash on feature extraction if an empty wav file is found

### CODE REVIEW

**Comment by shuttle1987** [comment]
Looks like I've run into this pip issue: https://github.com/pytest-dev/pytest/issues/3753
Essentially a transitive dependency isn't installing properly. I'll perhaps hack something together here but it's a situation I think pipenv solves properly.

**Comment by shuttle1987** [comment]
As far as I can tell this should be good to merge now.

**Comment by shuttle1987** [comment]
It looks like that issue is a different one to the one I fixed here, I definitely fixed a bug where the empty wav causes something in python-speech-features to have an index-error from a bad access of a numpy array. Looks like that was something else though...

**Comment by oadams** [comment]
Right, so until we have a solution that doesn't lead to other issues downstream, probably the best thing to do for now is just replace the warning with an exception that explains that the WAV is empty. Then it crashes and its clear why.

**Comment by shuttle1987** [comment]
Right, this isn't quite the same and I think that bailing out early on bad data will prevent issues from arising later if empty files are being included in the corpus.

**Comment by shuttle1987** [comment]
I like your exception message improvement :+1:

**Pull request merged**
