### PR TITLE
[MRG] Make optional arguments keyword args

### LINKED ISSUE #186: Move optional parameters into kwargs
Currently there's a few places where there are optional parameters that are not in kwargs. This means we can't pass optional parameters with defaults in a few places, once you skip an optional one there's no way to pass subsequent ones as positional.

Consider `Corpus.__init__`:
```
def __init__(self, feat_type: str, label_type: str, tgt_dir: Path, labels: Optional[Any] = None,
                 max_samples:int=1000, speakers: Optional[Sequence[str]] = None) -> None:
```

Here were must supply `labels` if we are supplying `speakers` or `max_samples`. This makes the code that is constructing calls from the API more difficult/messy.

### PR DESCRIPTION
**Pull request by shuttle1987**
Refactor argument handling for corpus initialization, Closes #186

### CODE REVIEW

**Comment by shuttle1987** [comment]
Note that this is a breaking change.

**Comment by shuttle1987** [comment]
This is the sort of thing we should merge sooner rather than later since it will give us much more flexibility with how the API is used going forward.

**Comment by oadams** [comment]
Okay, do you think I should merge it in now? Not sure because of the WIP tag in the title.

**Comment by shuttle1987** [comment]
I made those changes, test are not updated just yet. Note that this has the capacity to break things so a version bump is probably in order if this gets merged.

**Comment by shuttle1987** [comment]
I think this is good to go now.

**Pull request merged**
